# permissions for end users to view memleaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memleak-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memleaks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memleaks/status
  verbs:
  - get
